[workspace]
members = [
    "differentiable_market",
    "differentiable_market_kronos",
    "differentiable_market_totoembedding",
    "rlinc_market",
    "gymrl",
    "hfshared",
    "hfinference",
    "hftraining",
    "marketsimulator",
    "pufferlibinference",
    "pufferlibtraining",
    "pufferlibtraining2",
    "toto",
    "traininglib",
]
